/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/service-cases/create": {
    /**
     * Send Messages to Ibm Mq 
     * @description Send Message to the related ibm mq
     */
    post: operations["createServiceCase"];
  };
  "/service-cases/types": {
    get: operations["getServiceTypes"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    CreateServiceCaseDto: {
      deviceName?: string;
      caseType?: string;
      serialNumber?: string;
      message?: string;
      name?: string;
      surname?: string;
      email?: string;
      phone?: string;
      street?: string;
      houseNumber?: string;
      city?: string;
      postalCode?: string;
    };
    CodableDto: {
      code?: string;
      value?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  createServiceCase: {
    /**
     * Send Messages to Ibm Mq 
     * @description Send Message to the related ibm mq
     */
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateServiceCaseDto"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": number;
        };
      };
    };
  };
  getServiceTypes: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": (components["schemas"]["CodableDto"])[];
        };
      };
    };
  };
}
