spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  webflux:
    base-path: /admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: accounts.google.com

email:
  url: "localhost:5000/sendEmail"
  serviceCaseUrl: "localhost:8081/service-cases"