spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 357194755188-152tonbed8mcljmb28spg8759fol73rf.apps.googleusercontent.com
            client-secret: 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
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token

  webflux:
    base-path: /admin

