spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
server:
  port: 8081

email:
  url: "http://localhost:5000/default/send"
  serviceCaseUrl: "http://localhost:3000/detail"