spring:
  r2dbc:
    url: r2dbc:postgresql://PostgreSQL:5432/postgres
    username: postgres
    password: postgres
server:
  port: 8081

email:
  url: "http://mail:5000/default/send"
  serviceCaseUrl: "https://kappasupport.danielkrejci.cz/detail"
