/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CodableDto
 */
export interface CodableDto {
    /**
     * 
     * @type {string}
     * @memberof CodableDto
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof CodableDto
     */
    value?: string;
}

/**
 * Check if a given object implements the CodableDto interface.
 */
export function instanceOfCodableDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CodableDtoFromJSON(json: any): CodableDto {
    return CodableDtoFromJSONTyped(json, false);
}

export function CodableDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodableDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function CodableDtoToJSON(value?: CodableDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'value': value.value,
    };
}

