name: Build Server Projects

on:
  push:
  pull_request:

jobs:
  build-client:
    name: Build Client Project
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Checkout server directory
        uses: actions/checkout@v2
      - name: Build Client Project
        working-directory: server/client
        run: |
          chmod +x ./gradlew
          ./gradlew build
  build-admin:
    name: Build Admin Project
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Checkout server directory
        uses: actions/checkout@v2
      - name: Build Admin Project
        working-directory: server/admin
        run: |
          chmod +x ./gradlew
          ./gradlew build