name: Build Server Projects

on:
  push:
  pull_request:

jobs:
  build-client:
    name: Build Client Project
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Checkout server directory
        uses: actions/checkout@v2
      - name: Build Client Project
        working-directory: server/client
        run: |
          chmod +x ./gradlew
          ./gradlew build
      - name: Login to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push Client Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: server/client
        run: |
          docker build -t moizbot/mois-client:latest .
          docker push moizbot/mois-client:latest

  build-admin:
    name: Build Admin Project
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Checkout server directory
        uses: actions/checkout@v2
      - name: Build Admin Project
        working-directory: server/admin
        run: |
          chmod +x ./gradlew
          ./gradlew build
      - name: Login to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push Admin Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: server/admin
        run: |
          docker build -t moizbot/mois-admin:latest .
          docker push moizbot/mois-admin:latest

  build-web:
    name: Build Web Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout web directory
        uses: actions/checkout@v2
      - name: Install dependencies and build
        run: |
          cd web           
          yarn install
          yarn build
      - name: Login to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push Client Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          cd web
          docker build -t moizbot/mois-web:latest .
          docker push moizbot/mois-web:latest

